# Global Curvature Resonance CI Pipeline
# Implements verification tests for deployment safety

name: Global Curvature Resonance Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run unit tests
      run: |
        python -m pytest tests/ -v
    
    - name: Verify curvature modules
      run: |
        python src/field/curvature/tests.py
    
    - name: Simulate unattunement event
      run: |
        python ci/simulate_unattunement.py
    
    - name: Check GAS threshold
      run: |
        python ci/verify_gas_threshold.py

  deploy-validation:
    needs: build-and-test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Start field resonance services
      run: |
        ./start_field_resonance.sh &
        sleep 10  # Wait for services to start
    
    - name: Wait for stabilization
      run: |
        timeout 60 bash -c 'until curl -s http://localhost:5000/health | grep -q "stable"; do sleep 2; done'
    
    - name: Verify metrics thresholds
      run: |
        python ci/verify_metrics.py
    
    - name: Test safe mode activation
      run: |
        python ci/test_safe_mode.py
    
    - name: Validate heatmap updates
      run: |
        python ci/validate_heatmap.py